signatures = ["d3c976d4f3bab2e20f16c88aa46641af73256859d88b953aa1016ac0ace2e482"]
source = "Dot166"
hasFsVeritySignatures = true

description = """
FocusLock is a recreation of Googles DigitalWellbeing package, it is not feature complete with DigitalWellbeing but it is good enough for me
"""
