#!/bin/bash

set -o errexit -o nounset -o pipefail

if [[ $# -eq 1 ]]; then
    fd=$1
else
    touch lock
    exec {fd}< lock
fi

if ! flock -n $fd; then
    echo deploy_static already locked >&2
    exit 1
fi

rm -rf static-tmp
mkdir static-tmp #cp -a static static-tmp # no icons available so make directory
cp -a apps/* static-tmp

# drop unused sha256 and toml files while preserving directory timestamps
find static-tmp -regextype posix-extended -regex '.*\.(sha256|toml)' -delete
rsync -at --exclude '*.sha256' --exclude '*.toml' apps/ static-tmp

zopfli_preserve_time() {
    zopfli "$1"
    touch -r "$1" "$1.gz"
}
export -f zopfli_preserve_time

find static-tmp -regex '.+\.\(ico\|json\|sjson\|svg\)' |
    parallel -q ::: brotli zopfli_preserve_time :::: -

# update tv guide for iptv
git clone --depth 1 -b master https://github.com/dot166/epg.git # temporarily use my fork until https://github.com/iptv-org/epg/pull/3101 is merged
cd epg
npm install
npm run channels:parse --- --config=./sites/freeview.co.uk/freeview.co.uk.config.js --output=./sites/freeview.co.uk/freeview.co.uk.channels.xml
npm run grab --- --sites=freeview.co.uk --maxConnections=99 --output=../static-tmp/tv.xml
