/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "io.github.dot166.localers.AppKt"
}

tasks.jar {
    manifest {
        attributes("Main-Class" to "io.github.dot166.localers.AppKt")
    }
    val dependencies = configurations.runtimeClasspath.get()
        .map { if (it.isDirectory) it else zipTree(it) }

    from(dependencies)

    // Explicitly set the duplicate strategy to handle overlapping files
    // from different dependency jars (like META-INF files)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
