signatures = ["d3c976d4f3bab2e20f16c88aa46641af73256859d88b953aa1016ac0ace2e482"]
source = "Dot166"
hasFsVeritySignatures = true

description = """
App Store is the client for the GrapheneOS app repository. It's included in GrapheneOS but can also be used on other Android 12+ operating systems.
"""
