/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.dot166.localers

import java.util.Locale

class Main {
    fun constructLocaleFromString(localeString: String): Locale {
        val elements: Array<String?> =
            localeString.split("_".toRegex(), limit = 3).toTypedArray()
        val locale: Locale = when (elements.size) {
            1 -> {
                Locale(elements[0] /* language */)
            }
            2 -> {
                Locale(elements[0],  /* language */elements[1] /* country */)
            }
            else -> { // localeParams.length == 3
                Locale(
                    elements[0],  /* language */elements[1],  /* country */
                    elements[2] /* variant */
                )
            }
        }
        return locale
    }
    fun getSubtypeLocaleDisplayName(localeString: String): String {
        val displayLocale = constructLocaleFromString(localeString)
        val displayName: String = constructLocaleFromString(localeString).getDisplayName(displayLocale)
        return capitalizeFirstCodePoint(displayName, displayLocale)
    }
    fun capitalizeFirstCodePoint(s: String, locale: Locale): String {
        if (s.length <= 1) {
            return s.uppercase(getLocaleUsedForToTitleCase(locale))
        }
        // Please refer to the comment below in
        // {@link #capitalizeFirstAndDowncaseRest(String,Locale)} as this has the same shortcomings
        val cutoff = s.offsetByCodePoints(0, 1)
        return (s.substring(0, cutoff).uppercase(getLocaleUsedForToTitleCase(locale)) + s.substring(cutoff))
    }
    private fun getLocaleUsedForToTitleCase(locale: Locale): Locale {
        // In Greek locale {@link String#toUpperCase(Locale)} eliminates accents from its result.
        // In order to get accented upper case letter, {@link Locale#ROOT} should be used.
        if ("el" == locale.language) {
            return Locale.ROOT
        }
        return locale
    }
}

fun main(args: Array<String>) {
    println(Main().getSubtypeLocaleDisplayName(args[0]))
}
